# Generated by Django 2.0 on 2017-12-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('book', 'ordinal')},
        ),
    ]
