# Generated by Django 2.0 on 2017-12-11 19:16

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
        ('books', '0002_auto_20171211_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='bookmarks',
            field=mptt.fields.TreeManyToManyField(blank=True, to='bookmarks.Bookmark'),
        ),
    ]
