# Generated by Django 2.0 on 2018-04-09 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_track_bookmarks'),
        ('books', '0003_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='audio.Track'),
        ),
    ]
