# Generated by Django 2.0 on 2017-12-11 20:09

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_page_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='bookmarks',
            field=mptt.fields.TreeManyToManyField(blank=True, related_name='pages', to='bookmarks.Bookmark'),
        ),
    ]
