# Generated by Django 2.0.4 on 2018-04-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_annotation_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='end_page',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='start_page',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
