# Generated by Django 2.0.4 on 2018-04-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_set_start_end_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='short_summary',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='short summary'),
        ),
    ]
