# Generated by Django 2.0.4 on 2018-04-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_short_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='end_page',
            field=models.PositiveIntegerField(null=True, verbose_name='end page'),
        ),
        migrations.AlterField(
            model_name='book',
            name='start_page',
            field=models.PositiveIntegerField(null=True, verbose_name='start page'),
        ),
    ]
