# Generated by Django 2.0 on 2018-02-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('audio_url', models.URLField(unique=True, verbose_name='audio url')),
                ('length', models.DecimalField(decimal_places=2, help_text='in seconds', max_digits=10, verbose_name='length')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='summary')),
                ('doc_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='NLI document ID')),
            ],
        ),
    ]
