# Generated by Django 2.0 on 2018-02-04 11:09

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='bookmarks',
            field=mptt.fields.TreeManyToManyField(blank=True, related_name='tracks', to='bookmarks.Bookmark'),
        ),
    ]
