# Generated by Django 2.0.4 on 2018-04-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_auto_20180409_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_url',
            field=models.URLField(max_length=600, unique=True, verbose_name='audio url'),
        ),
    ]
